### ISSUE TITLE
Bug: Message reoccures "There isn't a config file yet"

### ISSUE THREAD

**Issue by ocbtec** [diqidoq/cpcam#1]
Even after succesfull first run of cpcam and entering source and target dir the application asks on every new start to setup the config file.

```
There isn't a config file yet. Please enter target and source path you want to use.
Source path: /home/user/Desktop
Target path: /home/user/New    

Checking '/home/user/New' ... 
 ... Path and folder exist.

Checking '/home/user/Desktop' ... 
 ... Path and folder exist.
/home/user/Desktop not empty.
sending incremental file list
created directory /home/user/New/160209_143426
./
tmp.txt
          7.52K 100%    0.00kB/s    0:00:00 (xfr#1, to-chk=0/2)

sent 7.64K bytes  received 88 bytes  15.46K bytes/sec
total size is 7.52K  speedup is 0.97

real    0m0.051s
user    0m0.000s
sys     0m0.008s
1 files copied.
1 original files found on the card.
```

System: Linux, Debian 9, XTerm 322, cpcam Masterbranch

**Comment by diqidoq** [comment]
Can confirm this on Linux/Debian 9 here. Seems there is simply a check failing. `if [ -d "$1" ] ; then` must always fail while looking for a file and not a directory of course :-) ...  I will dip into it. Since this utility is still in early BETA this is not a big surprise. Thanks for reporting back. Will fix this next hours and report back.

**Comment by ocbtec** [comment]
Thank you, that was really fast :)

**Comment by diqidoq** [comment]
yw
